### PR TITLE
fix: use URI.parse instead of URI.new! in normalize_url function to allow unescaped characters in the path

### PR DESCRIPTION
**Pull request by fahchen**
This PR depends on https://github.com/wojtekmach/req/pull/433.

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you for the PR. I tested this by modifying a test:

```diff
diff --git a/test/req_s3_test.exs b/test/req_s3_test.exs
index 5cb6380..b55cdb9 100644
--- a/test/req_s3_test.exs
+++ b/test/req_s3_test.exs
@@ -210,7 +210,7 @@ defmodule ReqS3Test do

     options = [
       bucket: bucket,
-      key: "key1",
+      key: "foo bar",
       content_type: "text/plain"
     ]

@@ -228,7 +228,7 @@ defmodule ReqS3Test do

     %{status: 200, body: ^body, headers: %{"content-type" => ["text/plain"]}} =
       Req.get!(
-        "#{form.url}/key1",
+        "#{form.url}/foo%20bar",
         aws_sigv4: [
           service: :s3,
           access_key_id: @access_key_id,
```

and I still got a `SignatureDoesNotMatch`. Could you double-check?

You can run integration tests like this:

```
$ BUCKET_NAME= REQ_AWS_ACCESS_KEY_ID= REQ_AWS_SECRET_ACCESS_KEY= mix test.all
```

I used latest Req main.

**Comment by fahchen** [comment]
@wojtekmach Thank you for testing it, I also got the same error using `Req.get!/2` with `aws_sigv4` options, but `ReqS3.presign_url/1` works as expected. I’ll dig deeper to resolve this issue.

```elixir
url = ReqS3.presign_url(bucket: bucket, key: "foo bar")

%{
  status: 200,
  body: ^body,
  headers: %{"content-type" => ["text/plain"]}
} = Req.get!(url)
```

**Comment by adriansalamon** [comment]
What is the status of this? I have the same issue, happy to help if any help is needed ☺️

**Comment by fahchen** [comment]
> What is the status of this? I have the same issue, happy to help if any help is needed ☺️

@adriansalamon This issue has been fixed in Req and a release is already available. In the meantime, here’s a workaround for this PR: you can pass a `URI` struct instead of a string.

for example:
```elixir
# Do this
ReqS3.presign_url([url: URI.parse("s3://wojtekmach-test/hello world.txt")])

# Not this
ReqS3.presign_url([url: "s3://wojtekmach-test/hello world.txt"])

```

@wojtekmach Should we provide a convenient way for users to pass a string instead of a URI struct? Do you have any suggestions? If it’s not necessary, I’ll go ahead and close this PR.

**Comment by wojtekmach** [comment]
Thanks for the PR, sorry for the delay!

**Pull request merged**
